---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: nfs-server-sc
  annotations:
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"
mountOptions:
  - nolock
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
    nfs-subdir-external-provisioner: nfs-provisioner-nfs-subdir-external-provisioner
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nolock
  nfs:
    server: nfs-server.nfs-system.svc.cluster.local
    path: /shared
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  selector:
    matchLabels:
      nfs-subdir-external-provisioner: nfs-provisioner-nfs-subdir-external-provisioner
  resources:
    requests:
      storage: 10Mi
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: nfs-provisioner-nfs-subdir-external-provisioner-runner
  namespace: nfs-system
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: run-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-system
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-nfs-subdir-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
  name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-system
roleRef:
  kind: Role
  name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-system
  labels:
    app: nfs-subdir-external-provisioner
    release: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-provisioner
  template:
    metadata:
      annotations:
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner-nfs-subdir-external-provisioner
      securityContext:
        {}
      containers:
        - name: nfs-subdir-external-provisioner
          image: "registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: nfs-server.nfs-system.svc.cluster.local
            - name: NFS_PATH
              value: /shared
      volumes:
        - name: nfs-subdir-external-provisioner-root
          persistentVolumeClaim:
            claimName: pvc-nfs-provisioner-nfs-subdir-external-provisioner

