apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: minio-vpa
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    app.kubernetes.io/version: 2025.7.23
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: minio
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "10m"
          memory: "128Mi"
        maxAllowed:
          cpu: "2"
          memory: "2Gi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.6.0
  name: postgres-postgresql-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: postgres-postgresql
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "50m"
          memory: "128Mi"
        maxAllowed:
          cpu: "1"
          memory: "1Gi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/component: run
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: mlflow
    app.kubernetes.io/version: 3.3.1
  name: mlflow-run-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mlflow-run
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "10m"
          memory: "128Mi"
        maxAllowed:
          cpu: "250m"
          memory: "512Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/component: tracking
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: mlflow
  name: mlflow-tracking-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mlflow-tracking
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "10m"
          memory: "128Mi"
        maxAllowed:
          cpu: "2"
          memory: "2Gi"
---

