apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nfs-server-vpa
  namespace: nfs-system
  labels:
    app.kubernetes.io/instance: nfs-server
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/version: 2.2.2
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: nfs-server
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "10m"
          memory: "50Mi"
        maxAllowed:
          cpu: "250m"
          memory: "500Mi"

