apiVersion: v1
kind: Namespace
metadata:
  name: nfs-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-system
  labels:
    app.kubernetes.io/instance: nfs-server
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/version: 2.2.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-server
      app.kubernetes.io/instance: nfs-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-server
        app.kubernetes.io/instance: nfs-server
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: nfs-server
          image: "ghcr.io/obeone/nfs-server:2.2.2"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
            privileged: true
          env:
            - name: NFS_EXPORT_0
              value: /shared *(rw,sync,no_subtree_check,no_root_squash)
            - name: TZ
              value: UTC
          ports:
            - name: nfs-111
              containerPort: 111
              protocol: TCP
            - name: nfs-32765
              containerPort: 32765
              protocol: TCP
            - name: nfs-32767
              containerPort: 32767
              protocol: TCP
            - name: nfsd
              containerPort: 2049
              protocol: TCP
            - name: nfs-111-udp
              containerPort: 111
              protocol: UDP
            - name: nfs-32765-udp
              containerPort: 32765
              protocol: UDP
            - name: nfs-32767-udp
              containerPort: 32767
              protocol: UDP
            - name: nfsd-udp
              containerPort: 2049
              protocol: UDP
          volumeMounts:
            - name: shared
              mountPath: /shared
          livenessProbe:
            tcpSocket:
              port: 2049
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 2049
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 2049
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: nfs-provider-pvc
