apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-system
  labels:
    app.kubernetes.io/instance: nfs-server
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/version: 2.2.2
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 111
    targetPort: nfs-111
    protocol: TCP
    name: nfs-111
  - port: 32765
    targetPort: nfs-32765
    protocol: TCP
    name: nfs-32765
  - port: 32767
    targetPort: nfs-32767
    protocol: TCP
    name: nfs-32767
  - port: 2049
    targetPort: nfsd
    protocol: TCP
    name: nfsd
  selector:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/instance: nfs-server
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-udp
  namespace: nfs-system
  labels:
    app.kubernetes.io/instance: nfs-server
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/version: 2.2.2
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 111
    targetPort: nfs-111-udp
    protocol: UDP
    name: nfs-111-udp
  - port: 32765
    targetPort: nfs-32765-udp
    protocol: UDP
    name: nfs-32765-udp
  - port: 32767
    targetPort: nfs-32767-udp
    protocol: UDP
    name: nfs-32767-udp
  - port: 2049
    targetPort: nfsd-udp
    protocol: UDP
    name: nfsd-udp
  selector:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/instance: nfs-server
