# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torch-serve-pvc
  namespace: default
  labels:
    app: torch-serve
spec:
  storageClassName: nfs-server-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
