# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: torch-serve-svc
  namespace: default
spec:
  selector:
    app: torch-serve
  type: ClusterIP
  ports:
  - name: model-serve
    protocol: TCP
    port: 80
    targetPort: 5000
